CXX = g++

SRCS = Poker.cpp Deck.cpp Card.cpp Player.cpp StudPoker.cpp go_drawPoker.cpp A3.cpp card_games.cpp

HEADERS = A3.h

program1: ${SRCS} ${HEADERS}

	${CXX} ${SRCS} -o A3

clean:

	rm -f *.o A3